// Centralized seed catalog for products + categories.
// Used by backend/config/database.js (auto-seed when empty) and backend/seed.js (manual seeding).

const img = (url, publicId) => ({ url, publicId });

// Use stable, high-quality royalty-free image URLs (Unsplash CDN with explicit photo IDs).
// All images are cropped consistently (fit=crop) to reduce layout shift.
const u = (photoId) =>
  `https://images.unsplash.com/${photoId}?auto=format&fit=crop&w=1200&q=80`;

const stamp = (iso) => ({ createdAt: new Date(iso), updatedAt: new Date(iso) });

export const seedCategories = [
  {
    name: 'Electronics',
    slug: 'electronics',
    description: 'Latest gadgets and electronic devices',
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400',
    isActive: true,
  },
  {
    name: 'Fashion',
    slug: 'fashion',
    description: 'Trendy clothing and accessories',
    image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=400',
    isActive: true,
  },
  {
    name: 'Home & Living',
    slug: 'home-living',
    description: 'Beautiful home decor and essentials',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400',
    isActive: true,
  },
  {
    name: 'Accessories',
    slug: 'accessories',
    description: 'Everyday add-ons and essentials for your devices',
    image: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400',
    isActive: true,
  },
];

// Products are expressed using the existing backend Product model shape.
// Extra “structured catalog” fields are included where supported (e.g., subCategory).
// Derived fields (title, discountPercentage, finalPrice, thumbnail, id, fullDescription) are exposed via schema virtuals.
export const seedProducts = [
  // ---------------------------------------------------------------------------
  // Electronics → Smartphones (4)
  // ---------------------------------------------------------------------------
  {
    name: 'Helio X Smartphone (256GB)',
    brand: 'Helio Mobile',
    slug: 'helio-x-smartphone-256gb',
    subCategory: 'Smartphones',
    description:
      'A premium smartphone built for fluid everyday performance. The OLED display stays readable outdoors, while the pro camera system captures natural skin tones and clean low‑light detail. Fast charging and efficient thermals keep it reliable for long workdays.',
    shortDescription: 'OLED display, pro camera, 256GB storage.',
    price: 899,
    compareAtPrice: 999,
    categorySlug: 'electronics',
    images: [
      img(u('photo-1511707171634-5f897ff02aa9'), 'seed-phone-helio-1'),
      img(u('photo-1510557880182-3d4d3c0c4b44'), 'seed-phone-helio-2'),
      img(u('photo-1526406915894-7bcd65f60845'), 'seed-phone-helio-3'),
      img(u('photo-1495433324511-bf8e92934d90'), 'seed-phone-helio-4'),
    ],
    sku: 'ELEC-PHN-HEL-256-001',
    stock: 26,
    tags: ['smartphone', 'oled', 'camera', 'fast-charging', '256gb'],
    isFeatured: true,
    rating: 4.7,
    reviewCount: 512,
    isActive: true,
    ...stamp('2026-02-02T07:45:00Z'),
  },
  {
    name: 'Vela Horizon Smartphone (128GB)',
    brand: 'Vela Mobile',
    slug: 'vela-horizon-smartphone-128gb',
    subCategory: 'Smartphones',
    description:
      'A balanced everyday smartphone with a bright OLED display and responsive performance. The camera system is tuned for natural HDR photos, while battery optimization keeps it dependable for full-day use.',
    shortDescription: 'Bright OLED, HDR photos, dependable all-day battery.',
    price: 729,
    compareAtPrice: 809,
    categorySlug: 'electronics',
    images: [
      img(u('photo-1512499617640-c2f999098c67'), 'seed-phone-vela-1'),
      img(u('photo-1512758017271-d7b84c2113f1'), 'seed-phone-vela-2'),
      img(u('photo-1526406915894-7bcd65f60845'), 'seed-phone-vela-3'),
      img(u('photo-1511707171634-5f897ff02aa9'), 'seed-phone-vela-4'),
    ],
    sku: 'ELEC-PHN-VEL-128-001',
    stock: 44,
    tags: ['smartphone', 'oled', 'hdr', 'battery', '128gb'],
    isFeatured: false,
    rating: 4.4,
    reviewCount: 264,
    isActive: true,
    ...stamp('2025-12-22T09:25:00Z'),
  },
  {
    name: 'Quanta Pro Smartphone (512GB)',
    brand: 'Quanta',
    slug: 'quanta-pro-smartphone-512gb',
    subCategory: 'Smartphones',
    description:
      'A flagship-grade smartphone built for creators: a high-refresh OLED panel, advanced video stabilization, and a roomy 512GB storage tier for 4K footage and large photo libraries. Tuned for fast multitasking and consistent thermals.',
    shortDescription: 'High-refresh OLED, stabilized video, 512GB storage.',
    price: 1079,
    compareAtPrice: 1179,
    categorySlug: 'electronics',
    images: [
      img(u('photo-1512499617640-c2f999098c67'), 'seed-phone-quanta-1'),
      img(u('photo-1511707171634-5f897ff02aa9'), 'seed-phone-quanta-2'),
      img(u('photo-1512758017271-d7b84c2113f1'), 'seed-phone-quanta-3'),
      img(u('photo-1495433324511-bf8e92934d90'), 'seed-phone-quanta-4'),
      img(u('photo-1526406915894-7bcd65f60845'), 'seed-phone-quanta-5'),
    ],
    sku: 'ELEC-PHN-QUA-512-001',
    stock: 19,
    tags: ['smartphone', 'oled', 'creator', '512gb', 'stabilization', 'high-refresh'],
    isFeatured: true,
    rating: 4.7,
    reviewCount: 689,
    isActive: true,
    ...stamp('2026-01-18T16:05:00Z'),
  },
  {
    name: 'Orion Lite Smartphone (5G)',
    brand: 'Orion Mobile',
    slug: 'orion-lite-smartphone-5g',
    subCategory: 'Smartphones',
    description:
      'A value-focused 5G phone with a smooth display and reliable battery. Great for messaging, streaming, and day-to-day productivity with fast connectivity and practical durability.',
    shortDescription: 'Reliable 5G phone with long battery life.',
    price: 399,
    compareAtPrice: 449,
    categorySlug: 'electronics',
    images: [
      img(u('photo-1511707171634-5f897ff02aa9'), 'seed-phone-orion-1'),
      img(u('photo-1510557880182-3d4d3c0c4b44'), 'seed-phone-orion-2'),
      img(u('photo-1495433324511-bf8e92934d90'), 'seed-phone-orion-3'),
    ],
    sku: 'ELEC-PHN-ORI-5G-001',
    stock: 92,
    tags: ['smartphone', '5g', 'budget', 'battery'],
    isFeatured: false,
    rating: 4.2,
    reviewCount: 156,
    isActive: true,
    ...stamp('2025-10-06T10:30:00Z'),
  },

  // Electronics → Smartphones (1)
  // ---------------------------------------------------------------------------
  {
    name: 'Cobalt Mini Smartphone',
    brand: 'Cobalt',
    slug: 'cobalt-mini-smartphone',
    subCategory: 'Smartphones',
    description:
      'A pocket-friendly smartphone with a sharp display and fast face unlock. Designed for one‑hand use without giving up performance for daily apps.',
    shortDescription: 'Pocket-friendly size with fast everyday performance.',
    price: 529,
    compareAtPrice: 599,
    categorySlug: 'electronics',
    images: [
      img(u('photo-1512758017271-d7b84c2113f1'), 'seed-phone-cobalt-1'),
      img(u('photo-1512499617640-c2f999098c67'), 'seed-phone-cobalt-2'),
      img(u('photo-1510557880182-3d4d3c0c4b44'), 'seed-phone-cobalt-3'),
      img(u('photo-1495433324511-bf8e92934d90'), 'seed-phone-cobalt-4'),
    ],
    sku: 'ELEC-PHN-COB-MINI-001',
    stock: 58,
    tags: ['smartphone', 'compact', 'one-hand', 'everyday'],
    isFeatured: false,
    rating: 4.3,
    reviewCount: 204,
    isActive: true,
    ...stamp('2025-11-21T14:20:00Z'),
  },

  // ---------------------------------------------------------------------------
  // Electronics → Laptops (4)
  // ---------------------------------------------------------------------------
  {
    name: 'NovaBook 14 Laptop (16GB/512GB)',
    brand: 'Nova Computing',
    slug: 'novabook-14-laptop-16gb-512gb',
    subCategory: 'Laptops',
    description:
      'A thin-and-light laptop designed for deep work. Quiet thermals, a color-accurate 14‑inch display, and a comfortable keyboard make it ideal for creators, students, and professionals.',
    shortDescription: '14" thin-and-light with all-day battery.',
    price: 1299,
    compareAtPrice: 1499,
    categorySlug: 'electronics',
    images: [
      img(u('photo-1515879218367-8466d910aaa4'), 'seed-laptop-nova-1'),
      img(u('photo-1498050108023-c5249f4df085'), 'seed-laptop-nova-2'),
      img(u('photo-1522202176988-66273c2fd55f'), 'seed-laptop-nova-3'),
      img(u('photo-1517336714731-489689fd1ca8'), 'seed-laptop-nova-4'),
    ],
    sku: 'ELEC-LAP-NOV-14512-001',
    stock: 19,
    tags: ['laptop', 'productivity', 'portable', '512gb', '16gb'],
    isFeatured: false,
    rating: 4.6,
    reviewCount: 141,
    isActive: true,
    ...stamp('2025-08-03T11:10:00Z'),
  },
  {
    name: 'Apex Studio Laptop 16 (32GB/1TB)',
    brand: 'Apex',
    slug: 'apex-studio-laptop-16-32gb-1tb',
    subCategory: 'Laptops',
    description:
      'A high-performance 16‑inch laptop for photo and video workflows. A bright, wide‑gamut panel and upgraded memory/storage keep large projects smooth, even with multi‑app setups.',
    shortDescription: '16" creator laptop with 32GB RAM and 1TB SSD.',
    price: 2199,
    compareAtPrice: 2399,
    categorySlug: 'electronics',
    images: [
      img(u('photo-1517336714731-489689fd1ca8'), 'seed-laptop-apex-1'),
      img(u('photo-1498050108023-c5249f4df085'), 'seed-laptop-apex-2'),
      img(u('photo-1515879218367-8466d910aaa4'), 'seed-laptop-apex-3'),
      img(u('photo-1518779578993-ec3579fee39f'), 'seed-laptop-apex-4'),
    ],
    sku: 'ELEC-LAP-APX-16ST-001',
    stock: 11,
    tags: ['laptop', 'creator', '16-inch', '1tb', '32gb'],
    isFeatured: true,
    rating: 4.7,
    reviewCount: 98,
    isActive: true,
    ...stamp('2025-09-19T08:35:00Z'),
  },
  {
    name: 'Summit Air Laptop 13 (8GB/256GB)',
    brand: 'Summit',
    slug: 'summit-air-laptop-13-8gb-256gb',
    subCategory: 'Laptops',
    description:
      'A lightweight 13‑inch laptop built for portability. Great for note taking, web apps, and travel with a crisp display and responsive trackpad.',
    shortDescription: 'Ultra-light 13" laptop for travel and study.',
    price: 899,
    compareAtPrice: 999,
    categorySlug: 'electronics',
    images: [
      img(u('photo-1515879218367-8466d910aaa4'), 'seed-laptop-summit-1'),
      img(u('photo-1522202176988-66273c2fd55f'), 'seed-laptop-summit-2'),
      img(u('photo-1498050108023-c5249f4df085'), 'seed-laptop-summit-3'),
    ],
    sku: 'ELEC-LAP-SUM-AIR13-001',
    stock: 34,
    tags: ['laptop', 'portable', '13-inch', 'student'],
    isFeatured: false,
    rating: 4.4,
    reviewCount: 212,
    isActive: true,
    ...stamp('2025-10-28T12:05:00Z'),
  },
  {
    name: 'Forge Gaming Laptop 15 (RTX)',
    brand: 'Forge',
    slug: 'forge-gaming-laptop-15-rtx',
    subCategory: 'Laptops',
    description:
      'A 15‑inch gaming laptop with high-refresh display and powerful graphics. Tuned cooling keeps performance stable during extended sessions and competitive play.',
    shortDescription: 'High-refresh 15" gaming laptop with dedicated graphics.',
    price: 1799,
    compareAtPrice: 1999,
    categorySlug: 'electronics',
    images: [
      img(u('photo-1527443154391-507e9dc6c5cc'), 'seed-laptop-forge-1'),
      img(u('photo-1518779578993-ec3579fee39f'), 'seed-laptop-forge-2'),
      img(u('photo-1517336714731-489689fd1ca8'), 'seed-laptop-forge-3'),
      img(u('photo-1498050108023-c5249f4df085'), 'seed-laptop-forge-4'),
    ],
    sku: 'ELEC-LAP-FRG-GAM15-001',
    stock: 14,
    tags: ['laptop', 'gaming', 'high-refresh', 'rtx'],
    isFeatured: true,
    rating: 4.6,
    reviewCount: 174,
    isActive: true,
    ...stamp('2025-12-03T17:00:00Z'),
  },

  // ---------------------------------------------------------------------------
  // Electronics → Headphones (4)
  // ---------------------------------------------------------------------------
  {
    name: 'Aurum Wireless Bluetooth Headphones',
    brand: 'Aurum Audio',
    slug: 'aurum-wireless-bluetooth-headphones',
    subCategory: 'Headphones',
    description:
      'Precision-tuned drivers and hybrid ANC deliver a focused, premium listening experience. Memory-foam ear cushions, multipoint Bluetooth, and a 30-hour battery keep you in the zone from commute to late-night sessions.',
    shortDescription: 'Hybrid ANC, 30-hour battery, premium comfort.',
    price: 279,
    compareAtPrice: 349,
    categorySlug: 'electronics',
    images: [
      img(u('photo-1505740420928-5e560c06d30e'), 'seed-headphones-aurum-1'),
      img(u('photo-1518444021444-7c7e9c6f7d29'), 'seed-headphones-aurum-2'),
      img(u('photo-1511367461989-f85a21fda167'), 'seed-headphones-aurum-3'),
      img(u('photo-1518441780351-4be1f6f1b3ea'), 'seed-headphones-aurum-4'),
    ],
    sku: 'ELEC-HEAD-AUR-001',
    stock: 64,
    tags: ['wireless', 'headphones', 'audio', 'noise-cancelling', 'bluetooth'],
    isFeatured: true,
    rating: 4.8,
    reviewCount: 312,
    isActive: true,
    ...stamp('2025-12-05T10:12:00Z'),
  },
  {
    name: 'Nimbus Studio Over‑Ear Headphones',
    brand: 'Nimbus Audio',
    slug: 'nimbus-studio-over-ear-headphones',
    subCategory: 'Headphones',
    description:
      'Balanced, studio-inspired tuning with wide soundstage and low fatigue. Comfortable clamp force and plush pads make it ideal for long editing sessions or relaxed late-night listening.',
    shortDescription: 'Studio tuning with plush comfort for long sessions.',
    price: 199,
    compareAtPrice: 249,
    categorySlug: 'electronics',
    images: [
      img(u('photo-1511367461989-f85a21fda167'), 'seed-headphones-nimbus-1'),
      img(u('photo-1505740420928-5e560c06d30e'), 'seed-headphones-nimbus-2'),
      img(u('photo-1518444021444-7c7e9c6f7d29'), 'seed-headphones-nimbus-3'),
    ],
    sku: 'ELEC-HEAD-NIM-001',
    stock: 82,
    tags: ['headphones', 'studio', 'over-ear', 'comfort'],
    isFeatured: false,
    rating: 4.5,
    reviewCount: 208,
    isActive: true,
    ...stamp('2025-11-02T13:44:00Z'),
  },
  {
    name: 'EchoFit Wireless Earbuds',
    brand: 'EchoFit',
    slug: 'echofit-wireless-earbuds',
    subCategory: 'Headphones',
    description:
      'Pocketable earbuds with secure fit and punchy sound. Quick pairing, stable connectivity, and sweat resistance for commutes, calls, and workouts.',
    shortDescription: 'Secure-fit earbuds with sweat resistance.',
    price: 89,
    compareAtPrice: 119,
    categorySlug: 'electronics',
    images: [
      img(u('photo-1590658268037-6bf12165a8df'), 'seed-earbuds-echo-1'),
      img(u('photo-1518444021444-7c7e9c6f7d29'), 'seed-earbuds-echo-2'),
      img(u('photo-1511367461989-f85a21fda167'), 'seed-earbuds-echo-3'),
      img(u('photo-1505740420928-5e560c06d30e'), 'seed-earbuds-echo-4'),
    ],
    sku: 'ELEC-HEAD-ECH-001',
    stock: 160,
    tags: ['earbuds', 'wireless', 'sweat-resistant', 'calls'],
    isFeatured: false,
    rating: 4.2,
    reviewCount: 541,
    isActive: true,
    ...stamp('2025-09-07T07:20:00Z'),
  },
  {
    name: 'Boreal ANC Headphones',
    brand: 'Boreal',
    slug: 'boreal-anc-headphones',
    subCategory: 'Headphones',
    description:
      'Hybrid noise cancellation with transparency mode for city commutes. Clear voice pickup and foldable design make it a dependable travel companion.',
    shortDescription: 'ANC + transparency with fold-flat portability.',
    price: 159,
    compareAtPrice: 199,
    categorySlug: 'electronics',
    images: [
      img(u('photo-1505740420928-5e560c06d30e'), 'seed-headphones-boreal-1'),
      img(u('photo-1518441780351-4be1f6f1b3ea'), 'seed-headphones-boreal-2'),
      img(u('photo-1518444021444-7c7e9c6f7d29'), 'seed-headphones-boreal-3'),
    ],
    sku: 'ELEC-HEAD-BOR-001',
    stock: 73,
    tags: ['headphones', 'anc', 'travel', 'bluetooth'],
    isFeatured: false,
    rating: 4.4,
    reviewCount: 329,
    isActive: true,
    ...stamp('2025-10-19T18:10:00Z'),
  },

  // ---------------------------------------------------------------------------
  // Electronics → Smart Watches (3)
  // ---------------------------------------------------------------------------
  {
    name: 'Zenith Smart Watch Pro',
    brand: 'Zenith Wear',
    slug: 'zenith-smart-watch-pro',
    subCategory: 'Smart Watches',
    description:
      'A premium smartwatch with a bright always-on display, dual-band GPS, advanced recovery metrics, and 7-day battery life. Designed to feel weightless while tracking everything that matters—workouts, sleep, stress, and daily activity.',
    shortDescription: 'Always-on display, dual-band GPS, 7-day battery.',
    price: 389,
    compareAtPrice: 449,
    categorySlug: 'electronics',
    images: [
      img(u('photo-1523275335684-37898b6baf30'), 'seed-watch-zenith-1'),
      img(u('photo-1544117519-31a4b719223d'), 'seed-watch-zenith-2'),
      img(u('photo-1508685096489-7aacd43bd3b1'), 'seed-watch-zenith-3'),
      img(u('photo-1517430816045-df4b7de11d1d'), 'seed-watch-zenith-4'),
    ],
    sku: 'ELEC-WAT-ZEN-001',
    stock: 78,
    tags: ['smartwatch', 'fitness', 'wearable', 'gps'],
    isFeatured: true,
    rating: 4.6,
    reviewCount: 198,
    isActive: true,
    ...stamp('2025-11-18T09:20:00Z'),
  },
  {
    name: 'Pulse Active Smart Watch',
    brand: 'Pulse',
    slug: 'pulse-active-smart-watch',
    subCategory: 'Smart Watches',
    description:
      'A lightweight fitness smartwatch with accurate heart-rate tracking, guided workouts, and sleep insights. Quick strap swap and bright display make it easy to wear day and night.',
    shortDescription: 'Fitness tracking, sleep insights, lightweight build.',
    price: 199,
    compareAtPrice: 239,
    categorySlug: 'electronics',
    images: [
      img(u('photo-1508685096489-7aacd43bd3b1'), 'seed-watch-pulse-1'),
      img(u('photo-1517430816045-df4b7de11d1d'), 'seed-watch-pulse-2'),
      img(u('photo-1523275335684-37898b6baf30'), 'seed-watch-pulse-3'),
    ],
    sku: 'ELEC-WAT-PUL-001',
    stock: 120,
    tags: ['smartwatch', 'fitness', 'sleep', 'heart-rate'],
    isFeatured: false,
    rating: 4.3,
    reviewCount: 344,
    isActive: true,
    ...stamp('2025-09-24T06:40:00Z'),
  },
  {
    name: 'ArcTime Classic Smart Watch',
    brand: 'ArcTime',
    slug: 'arctime-classic-smart-watch',
    subCategory: 'Smart Watches',
    description:
      'A classic-look smartwatch with stainless finish, call notifications, and health tracking. Designed to blend into office attire while still supporting daily wellness routines.',
    shortDescription: 'Classic design with notifications and health tracking.',
    price: 229,
    compareAtPrice: 269,
    categorySlug: 'electronics',
    images: [
      img(u('photo-1523275335684-37898b6baf30'), 'seed-watch-arctime-1'),
      img(u('photo-1544117519-31a4b719223d'), 'seed-watch-arctime-2'),
      img(u('photo-1508685096489-7aacd43bd3b1'), 'seed-watch-arctime-3'),
      img(u('photo-1517430816045-df4b7de11d1d'), 'seed-watch-arctime-4'),
    ],
    sku: 'ELEC-WAT-ARC-001',
    stock: 64,
    tags: ['smartwatch', 'classic', 'stainless', 'notifications'],
    isFeatured: false,
    rating: 4.4,
    reviewCount: 121,
    isActive: true,
    ...stamp('2025-08-11T19:15:00Z'),
  },

  // ---------------------------------------------------------------------------
  // Electronics → Monitors (3)
  // ---------------------------------------------------------------------------
  {
    name: 'Vista 27" 4K IPS Monitor',
    brand: 'Vista Display',
    slug: 'vista-27-4k-ips-monitor',
    subCategory: 'Monitors',
    description:
      'A crisp 27-inch 4K IPS panel with accurate color, smooth motion, and modern connectivity. Ideal for creators and professionals who want sharp text, rich contrast, and a clean desk aesthetic.',
    shortDescription: '27" 4K IPS, color-accurate, modern I/O.',
    price: 429,
    compareAtPrice: 499,
    categorySlug: 'electronics',
    images: [
      img(u('photo-1545239351-1141bd82e8a6'), 'seed-monitor-vista-1'),
      img(u('photo-1518779578993-ec3579fee39f'), 'seed-monitor-vista-2'),
      img(u('photo-1527443154391-507e9dc6c5cc'), 'seed-monitor-vista-3'),
      img(u('photo-1517336714731-489689fd1ca8'), 'seed-monitor-vista-4'),
    ],
    sku: 'ELEC-MON-VIS-27-001',
    stock: 37,
    tags: ['monitor', '4k', 'ips', 'workspace'],
    isFeatured: true,
    rating: 4.5,
    reviewCount: 164,
    isActive: true,
    ...stamp('2025-10-29T12:30:00Z'),
  },
  {
    name: 'CrispView 34" Ultrawide Monitor',
    brand: 'CrispView',
    slug: 'crispview-34-ultrawide-monitor',
    subCategory: 'Monitors',
    description:
      'An immersive 34-inch ultrawide monitor for multitasking—ideal for spreadsheets, timelines, and side-by-side docs. Smooth refresh and ergonomic stand support long work sessions.',
    shortDescription: '34" ultrawide for multitasking and clean setups.',
    price: 599,
    compareAtPrice: 699,
    categorySlug: 'electronics',
    images: [
      img(u('photo-1518779578993-ec3579fee39f'), 'seed-monitor-crisp-1'),
      img(u('photo-1545239351-1141bd82e8a6'), 'seed-monitor-crisp-2'),
      img(u('photo-1527443154391-507e9dc6c5cc'), 'seed-monitor-crisp-3'),
    ],
    sku: 'ELEC-MON-CRP-34-001',
    stock: 22,
    tags: ['monitor', 'ultrawide', 'productivity', 'workspace'],
    isFeatured: false,
    rating: 4.4,
    reviewCount: 96,
    isActive: true,
    ...stamp('2025-12-29T10:00:00Z'),
  },
  {
    name: 'FrameSync 24" Gaming Monitor',
    brand: 'FrameSync',
    slug: 'framesync-24-gaming-monitor',
    subCategory: 'Monitors',
    description:
      'A responsive 24-inch gaming monitor with low input lag and smooth motion. Great for competitive play with crisp clarity and a compact footprint.',
    shortDescription: 'Fast 24" gaming monitor with smooth motion.',
    price: 249,
    compareAtPrice: 299,
    categorySlug: 'electronics',
    images: [
      img(u('photo-1527443154391-507e9dc6c5cc'), 'seed-monitor-framesync-1'),
      img(u('photo-1518779578993-ec3579fee39f'), 'seed-monitor-framesync-2'),
      img(u('photo-1545239351-1141bd82e8a6'), 'seed-monitor-framesync-3'),
      img(u('photo-1517336714731-489689fd1ca8'), 'seed-monitor-framesync-4'),
    ],
    sku: 'ELEC-MON-FRS-24-001',
    stock: 48,
    tags: ['monitor', 'gaming', 'fast', 'low-latency'],
    isFeatured: false,
    rating: 4.5,
    reviewCount: 231,
    isActive: true,
    ...stamp('2025-11-11T05:30:00Z'),
  },

  // ---------------------------------------------------------------------------
  // Electronics → Gaming Accessories (3)
  // ---------------------------------------------------------------------------
  {
    name: 'Arcade Pro Mechanical Keyboard',
    brand: 'Arcade Labs',
    slug: 'arcade-pro-mechanical-keyboard',
    subCategory: 'Gaming Accessories',
    description:
      'A compact, premium mechanical keyboard with hot-swappable switches, gasket mount, and a dampened acoustic profile. Per-key RGB and multi-device connectivity make it equally at home on a gaming desk or a clean office setup.',
    shortDescription: 'Hot-swappable, gasket mount, deep acoustics.',
    price: 159,
    compareAtPrice: 199,
    categorySlug: 'electronics',
    images: [
      img(u('photo-1517336714731-489689fd1ca8'), 'seed-kbd-arcade-1'),
      img(u('photo-1587829741301-dc798b83add3'), 'seed-kbd-arcade-2'),
      img(u('photo-1541140134513-85a161dc4a00'), 'seed-kbd-arcade-3'),
      img(u('photo-1527443154391-507e9dc6c5cc'), 'seed-kbd-arcade-4'),
    ],
    sku: 'ELEC-GAM-KBD-ARC-001',
    stock: 142,
    tags: ['keyboard', 'mechanical', 'gaming', 'rgb'],
    isFeatured: false,
    rating: 4.7,
    reviewCount: 421,
    isActive: true,
    ...stamp('2026-01-07T15:00:00Z'),
  },
  {
    name: 'Vortex Precision Gaming Mouse',
    brand: 'Vortex',
    slug: 'vortex-precision-gaming-mouse',
    subCategory: 'Gaming Accessories',
    description:
      'A lightweight gaming mouse with crisp clicks and a consistent sensor. Tuned for control and comfort across long sessions with flexible cable and grippy coating.',
    shortDescription: 'Lightweight mouse with a consistent precision sensor.',
    price: 69,
    compareAtPrice: 89,
    categorySlug: 'electronics',
    images: [
      img(u('photo-1527443154391-507e9dc6c5cc'), 'seed-mouse-vortex-1'),
      img(u('photo-1518779578993-ec3579fee39f'), 'seed-mouse-vortex-2'),
      img(u('photo-1587829741301-dc798b83add3'), 'seed-mouse-vortex-3'),
    ],
    sku: 'ELEC-GAM-MOU-VOR-001',
    stock: 205,
    tags: ['mouse', 'gaming', 'lightweight', 'precision'],
    isFeatured: false,
    rating: 4.4,
    reviewCount: 388,
    isActive: true,
    ...stamp('2025-10-01T12:15:00Z'),
  },
  {
    name: 'Helix XL Mouse Pad (Desk Mat)',
    brand: 'Helix Gear',
    slug: 'helix-xl-mouse-pad-desk-mat',
    subCategory: 'Gaming Accessories',
    description:
      'An oversized desk mat with smooth glide and stitched edges. Protects your desk while providing a consistent surface for both mouse and keyboard.',
    shortDescription: 'Oversized desk mat with stitched edges.',
    price: 29,
    compareAtPrice: 39,
    categorySlug: 'electronics',
    images: [
      img(u('photo-1518779578993-ec3579fee39f'), 'seed-mat-helix-1'),
      img(u('photo-1527443154391-507e9dc6c5cc'), 'seed-mat-helix-2'),
      img(u('photo-1517336714731-489689fd1ca8'), 'seed-mat-helix-3'),
    ],
    sku: 'ELEC-GAM-MAT-HEL-001',
    stock: 330,
    tags: ['mousepad', 'desk-mat', 'gaming', 'accessory'],
    isFeatured: false,
    rating: 4.6,
    reviewCount: 1019,
    isActive: true,
    ...stamp('2025-07-05T09:00:00Z'),
  },

  // ---------------------------------------------------------------------------
  // Fashion → Men’s Shoes (4)
  // ---------------------------------------------------------------------------
  {
    name: 'Strider Men’s Running Shoes',
    brand: 'Strider Athletics',
    slug: 'strider-mens-running-shoes',
    subCategory: 'Men’s Shoes',
    description:
      'Responsive cushioning meets lightweight stability. Breathable upper, grippy outsole, and a smooth heel-to-toe transition built for daily miles—road runs, treadmill sessions, and weekend long distances.',
    shortDescription: 'Lightweight daily trainer with responsive cushioning.',
    price: 129,
    compareAtPrice: 149,
    categorySlug: 'fashion',
    images: [
      img(u('photo-1542291026-7eec264c27ff'), 'seed-men-shoes-strider-1'),
      img(u('photo-1528701800489-20be3c7a3b3f'), 'seed-men-shoes-strider-2'),
      img(u('photo-1600185365483-26d7a4cc7519'), 'seed-men-shoes-strider-3'),
      img(u('photo-1595950653106-6c9ebd614d3a'), 'seed-men-shoes-strider-4'),
    ],
    sku: 'FASH-MSH-STR-001',
    stock: 48,
    tags: ['mens', 'shoes', 'running', 'training'],
    isFeatured: true,
    rating: 4.4,
    reviewCount: 92,
    isActive: true,
    ...stamp('2025-12-21T18:05:00Z'),
  },
  {
    name: 'Cedar Men’s Leather Sneakers',
    brand: 'Cedar',
    slug: 'cedar-mens-leather-sneakers',
    subCategory: 'Men’s Shoes',
    description:
      'Minimal leather sneakers with a clean silhouette and cushioned insole. Designed to pair with denim, chinos, and smart-casual fits for everyday wear.',
    shortDescription: 'Minimal leather sneakers for smart-casual outfits.',
    price: 109,
    compareAtPrice: 139,
    categorySlug: 'fashion',
    images: [
      img(u('photo-1542291026-7eec264c27ff'), 'seed-men-shoes-cedar-1'),
      img(u('photo-1528701800489-20be3c7a3b3f'), 'seed-men-shoes-cedar-2'),
      img(u('photo-1600185365483-26d7a4cc7519'), 'seed-men-shoes-cedar-3'),
    ],
    sku: 'FASH-MSH-CED-001',
    stock: 66,
    tags: ['mens', 'shoes', 'sneakers', 'leather'],
    isFeatured: false,
    rating: 4.3,
    reviewCount: 173,
    isActive: true,
    ...stamp('2025-09-14T08:00:00Z'),
  },
  {
    name: 'Harbor Men’s Chelsea Boots',
    brand: 'Harbor',
    slug: 'harbor-mens-chelsea-boots',
    subCategory: 'Men’s Shoes',
    description:
      'Classic Chelsea boots crafted with durable materials and a comfortable footbed. A refined option for office days and weekend dinners with easy pull-on wear.',
    shortDescription: 'Classic Chelsea boots with all-day comfort.',
    price: 169,
    compareAtPrice: 199,
    categorySlug: 'fashion',
    images: [
      img(u('photo-1528701800489-20be3c7a3b3f'), 'seed-men-shoes-harbor-1'),
      img(u('photo-1542291026-7eec264c27ff'), 'seed-men-shoes-harbor-2'),
      img(u('photo-1595950653106-6c9ebd614d3a'), 'seed-men-shoes-harbor-3'),
    ],
    sku: 'FASH-MSH-HAR-001',
    stock: 29,
    tags: ['mens', 'boots', 'chelsea', 'classic'],
    isFeatured: false,
    rating: 4.5,
    reviewCount: 64,
    isActive: true,
    ...stamp('2025-11-08T10:10:00Z'),
  },
  {
    name: 'Ridge Men’s Trail Shoes',
    brand: 'Ridge',
    slug: 'ridge-mens-trail-shoes',
    subCategory: 'Men’s Shoes',
    description:
      'Trail-ready shoes with secure lockdown and grippy outsole for mixed terrain. Designed for stability on uneven paths while staying comfortable for longer walks.',
    shortDescription: 'Trail grip, stable fit, durable outsole.',
    price: 139,
    compareAtPrice: 159,
    categorySlug: 'fashion',
    images: [
      img(u('photo-1600185365483-26d7a4cc7519'), 'seed-men-shoes-ridge-1'),
      img(u('photo-1595950653106-6c9ebd614d3a'), 'seed-men-shoes-ridge-2'),
      img(u('photo-1542291026-7eec264c27ff'), 'seed-men-shoes-ridge-3'),
      img(u('photo-1528701800489-20be3c7a3b3f'), 'seed-men-shoes-ridge-4'),
    ],
    sku: 'FASH-MSH-RID-001',
    stock: 53,
    tags: ['mens', 'trail', 'shoes', 'outdoor'],
    isFeatured: false,
    rating: 4.2,
    reviewCount: 81,
    isActive: true,
    ...stamp('2025-10-02T06:30:00Z'),
  },

  // ---------------------------------------------------------------------------
  // Fashion → Women’s Sneakers (3)
  // ---------------------------------------------------------------------------
  {
    name: 'Luna Women’s Everyday Sneakers',
    brand: 'Luna',
    slug: 'luna-womens-everyday-sneakers',
    subCategory: 'Women’s Sneakers',
    description:
      'Versatile everyday sneakers with a breathable upper and supportive insole. Designed for comfort through errands, commutes, and long city walks.',
    shortDescription: 'Breathable sneakers made for all-day comfort.',
    price: 99,
    compareAtPrice: 129,
    categorySlug: 'fashion',
    images: [
      img(u('photo-1542291026-7eec264c27ff'), 'seed-womens-sneaker-luna-1'),
      img(u('photo-1600185365483-26d7a4cc7519'), 'seed-womens-sneaker-luna-2'),
      img(u('photo-1595950653106-6c9ebd614d3a'), 'seed-womens-sneaker-luna-3'),
    ],
    sku: 'FASH-WSN-LUN-001',
    stock: 88,
    tags: ['womens', 'sneakers', 'everyday', 'comfort'],
    isFeatured: false,
    rating: 4.4,
    reviewCount: 207,
    isActive: true,
    ...stamp('2025-09-26T12:00:00Z'),
  },
  {
    name: 'Aero Women’s Running Sneakers',
    brand: 'Aero',
    slug: 'aero-womens-running-sneakers',
    subCategory: 'Women’s Sneakers',
    description:
      'Lightweight running sneakers with smooth transitions and responsive foam. A secure midfoot fit keeps you stable through training blocks and daily jogs.',
    shortDescription: 'Lightweight runner with a secure midfoot fit.',
    price: 119,
    compareAtPrice: 149,
    categorySlug: 'fashion',
    images: [
      img(u('photo-1528701800489-20be3c7a3b3f'), 'seed-womens-sneaker-aero-1'),
      img(u('photo-1542291026-7eec264c27ff'), 'seed-womens-sneaker-aero-2'),
      img(u('photo-1595950653106-6c9ebd614d3a'), 'seed-womens-sneaker-aero-3'),
      img(u('photo-1600185365483-26d7a4cc7519'), 'seed-womens-sneaker-aero-4'),
    ],
    sku: 'FASH-WSN-AER-001',
    stock: 40,
    tags: ['womens', 'sneakers', 'running', 'training'],
    isFeatured: true,
    rating: 4.5,
    reviewCount: 118,
    isActive: true,
    ...stamp('2025-12-04T09:00:00Z'),
  },
  {
    name: 'Sable Women’s Retro Sneakers',
    brand: 'Sable',
    slug: 'sable-womens-retro-sneakers',
    subCategory: 'Women’s Sneakers',
    description:
      'Retro-inspired sneakers with suede accents and cushioned lining. Built to elevate casual outfits with a comfortable, walkable sole.',
    shortDescription: 'Retro styling with suede accents and cushioning.',
    price: 109,
    compareAtPrice: 139,
    categorySlug: 'fashion',
    images: [
      img(u('photo-1600185365483-26d7a4cc7519'), 'seed-womens-sneaker-sable-1'),
      img(u('photo-1542291026-7eec264c27ff'), 'seed-womens-sneaker-sable-2'),
      img(u('photo-1528701800489-20be3c7a3b3f'), 'seed-womens-sneaker-sable-3'),
    ],
    sku: 'FASH-WSN-SAB-001',
    stock: 57,
    tags: ['womens', 'sneakers', 'retro', 'suede'],
    isFeatured: false,
    rating: 4.3,
    reviewCount: 76,
    isActive: true,
    ...stamp('2025-08-18T06:12:00Z'),
  },

  // ---------------------------------------------------------------------------
  // Fashion → Backpacks (2)
  // ---------------------------------------------------------------------------
  {
    name: 'Nomad Premium Backpack (20L)',
    brand: 'Nomad Goods',
    slug: 'nomad-premium-backpack-20l',
    subCategory: 'Backpacks',
    description:
      'A premium, minimalist backpack built for daily carry. Water-resistant fabric, laptop protection, and quick-access organization keep your essentials secure without compromising a clean silhouette.',
    shortDescription: 'Minimal design, water-resistant, laptop-safe.',
    price: 119,
    compareAtPrice: 159,
    categorySlug: 'fashion',
    images: [
      img(u('photo-1553062407-98eeb64c6a62'), 'seed-backpack-nomad-1'),
      img(u('photo-1526481280695-3c687fd643ed'), 'seed-backpack-nomad-2'),
      img(u('photo-1526178613552-2b45c6c302f0'), 'seed-backpack-nomad-3'),
      img(u('photo-1542291026-7eec264c27ff'), 'seed-backpack-nomad-4'),
    ],
    sku: 'FASH-BAG-NOM-20-001',
    stock: 96,
    tags: ['backpack', 'travel', 'everyday-carry', 'laptop'],
    isFeatured: false,
    rating: 4.6,
    reviewCount: 241,
    isActive: true,
    ...stamp('2025-09-12T08:00:00Z'),
  },
  {
    name: 'Metro Commuter Backpack (28L)',
    brand: 'Metro',
    slug: 'metro-commuter-backpack-28l',
    subCategory: 'Backpacks',
    description:
      'A commuter backpack with structured organization: padded laptop sleeve, quick-access pocket, and breathable back panel. Designed for public transit and bike commutes.',
    shortDescription: 'Commuter pack with structured organization and padding.',
    price: 139,
    compareAtPrice: 169,
    categorySlug: 'fashion',
    images: [
      img(u('photo-1526481280695-3c687fd643ed'), 'seed-backpack-metro-1'),
      img(u('photo-1553062407-98eeb64c6a62'), 'seed-backpack-metro-2'),
      img(u('photo-1526178613552-2b45c6c302f0'), 'seed-backpack-metro-3'),
    ],
    sku: 'FASH-BAG-MET-28-001',
    stock: 52,
    tags: ['backpack', 'commuter', 'laptop', 'organization'],
    isFeatured: true,
    rating: 4.5,
    reviewCount: 112,
    isActive: true,
    ...stamp('2025-11-30T12:00:00Z'),
  },

  // ---------------------------------------------------------------------------
  // Fashion → Jackets (3)
  // ---------------------------------------------------------------------------
  {
    name: 'Northline Quilted Jacket',
    brand: 'Northline',
    slug: 'northline-quilted-jacket',
    subCategory: 'Jackets',
    description:
      'A lightweight quilted jacket designed for layering. Clean stitching, comfortable mobility, and practical warmth for cool mornings and evening walks.',
    shortDescription: 'Lightweight quilted jacket for easy layering.',
    price: 149,
    compareAtPrice: 189,
    categorySlug: 'fashion',
    images: [
      img(u('photo-1520975958225-0f6d3b4d2b4b'), 'seed-jacket-northline-1'),
      img(u('photo-1520975958225-0f6d3b4d2b4b'), 'seed-jacket-northline-2'),
      img(u('photo-1520975958225-0f6d3b4d2b4b'), 'seed-jacket-northline-3'),
    ],
    sku: 'FASH-JKT-NOR-001',
    stock: 38,
    tags: ['jacket', 'quilted', 'layering', 'outerwear'],
    isFeatured: false,
    rating: 4.2,
    reviewCount: 59,
    isActive: true,
    ...stamp('2025-10-12T18:30:00Z'),
  },
  {
    name: 'Harbor Windbreaker Jacket',
    brand: 'Harbor',
    slug: 'harbor-windbreaker-jacket',
    subCategory: 'Jackets',
    description:
      'A packable windbreaker with a clean fit and water-repellent finish. Great for unpredictable weather—easy to toss in a bag and wear on the go.',
    shortDescription: 'Packable windbreaker with water-repellent finish.',
    price: 99,
    compareAtPrice: 129,
    categorySlug: 'fashion',
    images: [
      img(u('photo-1520975958225-0f6d3b4d2b4b'), 'seed-jacket-harbor-1'),
      img(u('photo-1520975958225-0f6d3b4d2b4b'), 'seed-jacket-harbor-2'),
      img(u('photo-1520975958225-0f6d3b4d2b4b'), 'seed-jacket-harbor-3'),
    ],
    sku: 'FASH-JKT-HAR-001',
    stock: 74,
    tags: ['jacket', 'windbreaker', 'outerwear', 'packable'],
    isFeatured: true,
    rating: 4.4,
    reviewCount: 131,
    isActive: true,
    ...stamp('2025-09-01T07:05:00Z'),
  },
  {
    name: 'Evergreen Denim Jacket',
    brand: 'Evergreen',
    slug: 'evergreen-denim-jacket',
    subCategory: 'Jackets',
    description:
      'A classic denim jacket with a modern fit and durable fabric. Works year-round as a layering piece with tees, hoodies, and knits.',
    shortDescription: 'Classic denim jacket with a modern fit.',
    price: 119,
    compareAtPrice: 149,
    categorySlug: 'fashion',
    images: [
      img(u('photo-1520975958225-0f6d3b4d2b4b'), 'seed-jacket-evergreen-1'),
      img(u('photo-1520975958225-0f6d3b4d2b4b'), 'seed-jacket-evergreen-2'),
      img(u('photo-1520975958225-0f6d3b4d2b4b'), 'seed-jacket-evergreen-3'),
    ],
    sku: 'FASH-JKT-EVG-001',
    stock: 44,
    tags: ['jacket', 'denim', 'classic', 'layering'],
    isFeatured: false,
    rating: 4.3,
    reviewCount: 83,
    isActive: true,
    ...stamp('2025-08-22T10:00:00Z'),
  },

  // ---------------------------------------------------------------------------
  // Fashion → Watches (2)
  // ---------------------------------------------------------------------------
  {
    name: 'Mariner Minimal Watch',
    brand: 'Mariner',
    slug: 'mariner-minimal-watch',
    subCategory: 'Watches',
    description:
      'A minimalist analog watch with a slim profile and clean dial. Designed to complement office and weekend outfits with understated style.',
    shortDescription: 'Minimal analog watch with slim profile and clean dial.',
    price: 89,
    compareAtPrice: 109,
    categorySlug: 'fashion',
    images: [
      img(u('photo-1523275335684-37898b6baf30'), 'seed-fashion-watch-mariner-1'),
      img(u('photo-1544117519-31a4b719223d'), 'seed-fashion-watch-mariner-2'),
      img(u('photo-1508685096489-7aacd43bd3b1'), 'seed-fashion-watch-mariner-3'),
    ],
    sku: 'FASH-WAT-MAR-001',
    stock: 101,
    tags: ['watch', 'analog', 'minimal', 'accessory'],
    isFeatured: false,
    rating: 4.4,
    reviewCount: 226,
    isActive: true,
    ...stamp('2025-07-18T08:10:00Z'),
  },
  {
    name: 'Sable Leather Strap Watch',
    brand: 'Sable',
    slug: 'sable-leather-strap-watch',
    subCategory: 'Watches',
    description:
      'A classic watch with leather strap and a balanced dial layout. Comfortable for daily wear and designed to look polished without feeling flashy.',
    shortDescription: 'Classic leather strap watch with balanced dial.',
    price: 119,
    compareAtPrice: 149,
    categorySlug: 'fashion',
    images: [
      img(u('photo-1544117519-31a4b719223d'), 'seed-fashion-watch-sable-1'),
      img(u('photo-1523275335684-37898b6baf30'), 'seed-fashion-watch-sable-2'),
      img(u('photo-1517430816045-df4b7de11d1d'), 'seed-fashion-watch-sable-3'),
    ],
    sku: 'FASH-WAT-SAB-001',
    stock: 67,
    tags: ['watch', 'leather', 'classic', 'accessory'],
    isFeatured: true,
    rating: 4.5,
    reviewCount: 119,
    isActive: true,
    ...stamp('2025-12-09T11:40:00Z'),
  },

  // ---------------------------------------------------------------------------
  // Home & Living → Desk Lamps (2)
  // ---------------------------------------------------------------------------
  {
    name: 'Luma Ceramic Table Lamp',
    brand: 'Luma Home',
    slug: 'luma-ceramic-table-lamp',
    subCategory: 'Desk Lamps',
    description:
      'A warm, modern table lamp with a handcrafted ceramic base and a softly diffused shade. Adjustable brightness makes it perfect for reading corners, bedside tables, and minimalist workspaces.',
    shortDescription: 'Handcrafted ceramic base, adjustable brightness.',
    price: 89,
    compareAtPrice: 109,
    categorySlug: 'home-living',
    images: [
      img(u('photo-1507473885765-e6ed057f782c'), 'seed-lamp-luma-1'),
      img(u('photo-1540932239986-30128078f3c1'), 'seed-lamp-luma-2'),
      img(u('photo-1524758631624-e2822e304c36'), 'seed-lamp-luma-3'),
      img(u('photo-1505693416388-ac5ce068fe85'), 'seed-lamp-luma-4'),
    ],
    sku: 'HOME-LMP-LUM-001',
    stock: 41,
    tags: ['lamp', 'home', 'lighting', 'decor'],
    isFeatured: false,
    rating: 4.4,
    reviewCount: 72,
    isActive: true,
    ...stamp('2025-06-15T20:10:00Z'),
  },
  {
    name: 'Arc LED Desk Lamp (USB-C)',
    brand: 'Arc Home',
    slug: 'arc-led-desk-lamp-usb-c',
    subCategory: 'Desk Lamps',
    description:
      'A sleek LED desk lamp with adjustable color temperature and brightness. USB‑C power and a compact base make it ideal for small desks and modern workspaces.',
    shortDescription: 'Adjustable LED desk lamp with USB-C power.',
    price: 49,
    compareAtPrice: 69,
    categorySlug: 'home-living',
    images: [
      img(u('photo-1524758631624-e2822e304c36'), 'seed-lamp-arc-1'),
      img(u('photo-1505693416388-ac5ce068fe85'), 'seed-lamp-arc-2'),
      img(u('photo-1507473885765-e6ed057f782c'), 'seed-lamp-arc-3'),
    ],
    sku: 'HOME-LMP-ARC-001',
    stock: 95,
    tags: ['lamp', 'desk', 'led', 'usb-c', 'workspace'],
    isFeatured: true,
    rating: 4.5,
    reviewCount: 144,
    isActive: true,
    ...stamp('2025-11-16T09:10:00Z'),
  },

  // ---------------------------------------------------------------------------
  // Home & Living → Office Chairs (2)
  // ---------------------------------------------------------------------------
  {
    name: 'ErgoCloud Mesh Office Chair',
    brand: 'ErgoCloud',
    slug: 'ergocloud-mesh-office-chair',
    subCategory: 'Office Chairs',
    description:
      'An ergonomic mesh chair with breathable backrest, adjustable lumbar support, and smooth-rolling casters. Built for comfortable posture during long work sessions.',
    shortDescription: 'Breathable mesh, adjustable lumbar support.',
    price: 249,
    compareAtPrice: 299,
    categorySlug: 'home-living',
    images: [
      img(u('photo-1586023492125-27b2c045efd7'), 'seed-chair-ergocloud-1'),
      img(u('photo-1524758631624-e2822e304c36'), 'seed-chair-ergocloud-2'),
      img(u('photo-1505693416388-ac5ce068fe85'), 'seed-chair-ergocloud-3'),
    ],
    sku: 'HOME-CHR-ERG-001',
    stock: 26,
    tags: ['office', 'chair', 'ergonomic', 'mesh'],
    isFeatured: true,
    rating: 4.6,
    reviewCount: 318,
    isActive: true,
    ...stamp('2025-10-20T12:00:00Z'),
  },
  {
    name: 'Oakline Padded Office Chair',
    brand: 'Oakline',
    slug: 'oakline-padded-office-chair',
    subCategory: 'Office Chairs',
    description:
      'A comfortable padded chair with supportive cushioning and a clean silhouette. Designed for home offices with adjustable height and durable upholstery.',
    shortDescription: 'Supportive padded chair for home offices.',
    price: 199,
    compareAtPrice: 239,
    categorySlug: 'home-living',
    images: [
      img(u('photo-1505693416388-ac5ce068fe85'), 'seed-chair-oakline-1'),
      img(u('photo-1586023492125-27b2c045efd7'), 'seed-chair-oakline-2'),
      img(u('photo-1524758631624-e2822e304c36'), 'seed-chair-oakline-3'),
    ],
    sku: 'HOME-CHR-OAK-001',
    stock: 19,
    tags: ['office', 'chair', 'padded', 'home-office'],
    isFeatured: false,
    rating: 4.3,
    reviewCount: 104,
    isActive: true,
    ...stamp('2025-09-03T11:05:00Z'),
  },

  // ---------------------------------------------------------------------------
  // Home & Living → Wall Art (2)
  // ---------------------------------------------------------------------------
  {
    name: 'Monochrome Lines Wall Art Print',
    brand: 'Studio Mono',
    slug: 'monochrome-lines-wall-art-print',
    subCategory: 'Wall Art',
    description:
      'A modern monochrome wall art print with clean lines and a calm composition. Works well for minimalist living rooms, hallways, and office walls.',
    shortDescription: 'Modern monochrome print for minimalist spaces.',
    price: 39,
    compareAtPrice: 49,
    categorySlug: 'home-living',
    images: [
      img(u('photo-1526481280695-3c687fd643ed'), 'seed-art-mono-1'),
      img(u('photo-1524758631624-e2822e304c36'), 'seed-art-mono-2'),
      img(u('photo-1507473885765-e6ed057f782c'), 'seed-art-mono-3'),
    ],
    sku: 'HOME-ART-MON-001',
    stock: 120,
    tags: ['wall-art', 'print', 'decor', 'minimal'],
    isFeatured: false,
    rating: 4.2,
    reviewCount: 41,
    isActive: true,
    ...stamp('2025-07-02T08:00:00Z'),
  },
  {
    name: 'Warm Abstract Wall Art Poster',
    brand: 'Atelier Warm',
    slug: 'warm-abstract-wall-art-poster',
    subCategory: 'Wall Art',
    description:
      'An abstract wall art poster with warm tones designed to add depth to neutral interiors. Printed with crisp detail for a clean, modern look.',
    shortDescription: 'Warm-toned abstract poster for modern interiors.',
    price: 45,
    compareAtPrice: 59,
    categorySlug: 'home-living',
    images: [
      img(u('photo-1524758631624-e2822e304c36'), 'seed-art-warm-1'),
      img(u('photo-1526481280695-3c687fd643ed'), 'seed-art-warm-2'),
      img(u('photo-1586023492125-27b2c045efd7'), 'seed-art-warm-3'),
    ],
    sku: 'HOME-ART-WRM-001',
    stock: 85,
    tags: ['wall-art', 'poster', 'abstract', 'decor'],
    isFeatured: true,
    rating: 4.4,
    reviewCount: 58,
    isActive: true,
    ...stamp('2025-12-15T18:00:00Z'),
  },

  // ---------------------------------------------------------------------------
  // Home & Living → Storage Organizers (2)
  // ---------------------------------------------------------------------------
  {
    name: 'StackSmart Drawer Organizer Set',
    brand: 'StackSmart',
    slug: 'stacksmart-drawer-organizer-set',
    subCategory: 'Storage Organizers',
    description:
      'Modular drawer organizers to keep cables, stationery, and small items neatly separated. Durable, easy to wipe clean, and designed to mix-and-match for different drawer sizes.',
    shortDescription: 'Modular organizers for tidy drawers and desks.',
    price: 29,
    compareAtPrice: 39,
    categorySlug: 'home-living',
    images: [
      img(u('photo-1524758631624-e2822e304c36'), 'seed-org-stack-1'),
      img(u('photo-1505693416388-ac5ce068fe85'), 'seed-org-stack-2'),
      img(u('photo-1586023492125-27b2c045efd7'), 'seed-org-stack-3'),
    ],
    sku: 'HOME-ORG-STK-001',
    stock: 210,
    tags: ['storage', 'organizer', 'desk', 'home'],
    isFeatured: false,
    rating: 4.3,
    reviewCount: 133,
    isActive: true,
    ...stamp('2025-08-06T10:00:00Z'),
  },
  {
    name: 'ClearView Closet Organizer Bins (4-Pack)',
    brand: 'ClearView',
    slug: 'clearview-closet-organizer-bins-4-pack',
    subCategory: 'Storage Organizers',
    description:
      'Clear bins designed for closets, pantries, and shelves. The transparent walls make it easy to find items quickly, while the stackable design keeps spaces organized.',
    shortDescription: 'Stackable clear bins for closets and pantries.',
    price: 34,
    compareAtPrice: 44,
    categorySlug: 'home-living',
    images: [
      img(u('photo-1586023492125-27b2c045efd7'), 'seed-org-clear-1'),
      img(u('photo-1505693416388-ac5ce068fe85'), 'seed-org-clear-2'),
      img(u('photo-1524758631624-e2822e304c36'), 'seed-org-clear-3'),
    ],
    sku: 'HOME-ORG-CLV-001',
    stock: 170,
    tags: ['storage', 'bins', 'organizer', 'closet'],
    isFeatured: true,
    rating: 4.5,
    reviewCount: 209,
    isActive: true,
    ...stamp('2025-11-26T07:15:00Z'),
  },

  // ---------------------------------------------------------------------------
  // Accessories → Power Banks (2)
  // ---------------------------------------------------------------------------
  {
    name: 'Volt 20,000mAh Power Bank (USB-C PD)',
    brand: 'Volt Supply',
    slug: 'volt-20000mah-power-bank-usb-c-pd',
    subCategory: 'Power Banks',
    description:
      'A travel-ready power bank with high-density cells, fast USB‑C Power Delivery, and a durable aluminum shell. Charge your phone multiple times or top up accessories without hunting for an outlet.',
    shortDescription: 'Fast USB-C PD, premium aluminum body.',
    price: 69,
    compareAtPrice: 89,
    categorySlug: 'accessories',
    images: [
      img(u('photo-1586953208448-b95a79798f07'), 'seed-pb-volt-1'),
      img(u('photo-1555617117-08c0c3f85c53'), 'seed-pb-volt-2'),
      img(u('photo-1526406915894-7bcd65f60845'), 'seed-pb-volt-3'),
      img(u('photo-1510557880182-3d4d3c0c4b44'), 'seed-pb-volt-4'),
    ],
    sku: 'ACC-PB-VOL-20000-001',
    stock: 210,
    tags: ['power-bank', 'usb-c', 'travel', 'battery'],
    isFeatured: true,
    rating: 4.6,
    reviewCount: 612,
    isActive: true,
    ...stamp('2026-01-22T13:15:00Z'),
  },
  {
    name: 'SwiftCharge 10,000mAh Slim Power Bank',
    brand: 'SwiftCharge',
    slug: 'swiftcharge-10000mah-slim-power-bank',
    subCategory: 'Power Banks',
    description:
      'A slim, pocket-friendly power bank with fast charging and a soft-touch finish. Ideal for daily commutes and travel days when you need a compact backup battery.',
    shortDescription: 'Slim 10,000mAh power bank for daily carry.',
    price: 39,
    compareAtPrice: 49,
    categorySlug: 'accessories',
    images: [
      img(u('photo-1555617117-08c0c3f85c53'), 'seed-pb-swift-1'),
      img(u('photo-1586953208448-b95a79798f07'), 'seed-pb-swift-2'),
      img(u('photo-1510557880182-3d4d3c0c4b44'), 'seed-pb-swift-3'),
    ],
    sku: 'ACC-PB-SWF-10000-001',
    stock: 320,
    tags: ['power-bank', 'slim', 'portable', 'usb-c'],
    isFeatured: false,
    rating: 4.4,
    reviewCount: 473,
    isActive: true,
    ...stamp('2025-10-07T08:05:00Z'),
  },

  // ---------------------------------------------------------------------------
  // Accessories → USB Hubs (1)
  // ---------------------------------------------------------------------------
  {
    name: 'PortFlex 7‑in‑1 USB‑C Hub',
    brand: 'PortFlex',
    slug: 'portflex-7-in-1-usb-c-hub',
    subCategory: 'USB Hubs',
    description:
      'A compact USB‑C hub with HDMI, USB‑A, USB‑C pass-through charging, and card reader. Built for laptops with fewer ports—clean desk setup with reliable connectivity.',
    shortDescription: '7-in-1 USB-C hub with HDMI and pass-through charging.',
    price: 49,
    compareAtPrice: 69,
    categorySlug: 'accessories',
    images: [
      img(u('photo-1518779578993-ec3579fee39f'), 'seed-hub-portflex-1'),
      img(u('photo-1517336714731-489689fd1ca8'), 'seed-hub-portflex-2'),
      img(u('photo-1527443154391-507e9dc6c5cc'), 'seed-hub-portflex-3'),
    ],
    sku: 'ACC-HUB-PRT-7IN1-001',
    stock: 145,
    tags: ['usb-c', 'hub', 'hdmi', 'adapter'],
    isFeatured: true,
    rating: 4.5,
    reviewCount: 189,
    isActive: true,
    ...stamp('2025-12-28T07:00:00Z'),
  },

  // ---------------------------------------------------------------------------
  // Accessories → Phone Cases (2)
  // ---------------------------------------------------------------------------
  {
    name: 'ShieldClear Phone Case (Transparent)',
    brand: 'ShieldClear',
    slug: 'shieldclear-phone-case-transparent',
    subCategory: 'Phone Cases',
    description:
      'A transparent phone case with shock-absorbing corners and a slim profile. Designed to protect without hiding your phone’s finish.',
    shortDescription: 'Slim transparent case with shock-absorbing corners.',
    price: 19,
    compareAtPrice: 25,
    categorySlug: 'accessories',
    images: [
      img(u('photo-1511707171634-5f897ff02aa9'), 'seed-case-clear-1'),
      img(u('photo-1510557880182-3d4d3c0c4b44'), 'seed-case-clear-2'),
      img(u('photo-1512758017271-d7b84c2113f1'), 'seed-case-clear-3'),
    ],
    sku: 'ACC-CAS-CLR-001',
    stock: 500,
    tags: ['phone-case', 'transparent', 'protection', 'slim'],
    isFeatured: false,
    rating: 4.3,
    reviewCount: 1002,
    isActive: true,
    ...stamp('2025-07-12T11:00:00Z'),
  },
  {
    name: 'GripGuard Phone Case (Matte)',
    brand: 'GripGuard',
    slug: 'gripguard-phone-case-matte',
    subCategory: 'Phone Cases',
    description:
      'A matte phone case with grippy texture and precise cutouts. Designed to resist fingerprints and provide reliable drop protection.',
    shortDescription: 'Matte grippy case with precise cutouts.',
    price: 22,
    compareAtPrice: 29,
    categorySlug: 'accessories',
    images: [
      img(u('photo-1510557880182-3d4d3c0c4b44'), 'seed-case-matte-1'),
      img(u('photo-1511707171634-5f897ff02aa9'), 'seed-case-matte-2'),
      img(u('photo-1495433324511-bf8e92934d90'), 'seed-case-matte-3'),
    ],
    sku: 'ACC-CAS-GRP-001',
    stock: 420,
    tags: ['phone-case', 'matte', 'grip', 'protection'],
    isFeatured: true,
    rating: 4.5,
    reviewCount: 611,
    isActive: true,
    ...stamp('2025-11-04T09:40:00Z'),
  },

  // ---------------------------------------------------------------------------
  // Accessories → Portable Speakers (1)
  // ---------------------------------------------------------------------------
  {
    name: 'Pulse Portable Speaker',
    brand: 'Pulse Sound',
    slug: 'pulse-portable-speaker',
    subCategory: 'Portable Speakers',
    description:
      'Compact size, surprisingly full sound. A portable speaker with rich bass, 360° audio tuning, and an IP-rated shell for outdoor days. USB‑C fast charging and long playback keep the music going.',
    shortDescription: '360° sound, IP-rated, 18-hour battery.',
    price: 149,
    compareAtPrice: 179,
    categorySlug: 'accessories',
    images: [
      img(u('photo-1545454675-3531b543be5d'), 'seed-speaker-pulse-1'),
      img(u('photo-1518444021444-7c7e9c6f7d29'), 'seed-speaker-pulse-2'),
      img(u('photo-1511367461989-f85a21fda167'), 'seed-speaker-pulse-3'),
      img(u('photo-1526178613552-2b45c6c302f0'), 'seed-speaker-pulse-4'),
    ],
    sku: 'ACC-SPK-PUL-001',
    stock: 54,
    tags: ['speaker', 'portable', 'bluetooth', 'audio'],
    isFeatured: false,
    rating: 4.3,
    reviewCount: 206,
    isActive: true,
    ...stamp('2025-07-23T16:40:00Z'),
  },
];

// NOTE: This catalog currently contains 50 structured products.
// (Kept centralized so the UI + API stay consistent and the seed remains idempotent.)
